import { z } from "zod";
import { phoneRegex } from "@/lib/validations/shared";
import { isPesonetBank } from "@/lib/payouts/pesonetBanks";

export const submitOwnerApplicationSchema = z
  .object({
    businessName: z.string().trim().min(2, "Enter your name or business name").max(120),
    businessPhone: z.string().trim().regex(phoneRegex, "Enter a valid phone number"),
    businessEmail: z.email("Enter a valid email address"),
    venueName: z.string().trim().min(2, "Enter your venue's name").max(120),
    venueAddress: z.string().trim().min(1, "Enter a street address").max(200),
    venueCity: z.string().trim().min(1, "Enter a city").max(100),
    venueDescription: z.string().trim().max(2000).optional(),
    // Paired with `register("courtCount", { valueAsNumber: true })` so
    // react-hook-form converts the input value before validation — same
    // reasoning createVenueDraftSchema's numberOfCourts field documents.
    courtCount: z.number().int().min(1, "Must have at least 1 court").max(100),
    // Left undefined (not defaulted) until the applicant actually answers
    // — `false` is itself a valid, meaningful answer under Owner Agreement
    // clause 5.3, so it must never be indistinguishable from "unanswered."
    // The custom `error` message replaces Zod's default "expected boolean,
    // received undefined" — verified empirically, since a `.refine()`
    // here would never run: the base invalid_type check rejects undefined
    // before any refine gets a chance to.
    hasLiabilityInsurance: z.boolean({ error: "Let us know whether your venue carries public liability insurance." }),
    // Payout destination. Required to submit — an approved owner with no
    // way to receive money is the gap migration 20260810000090 exists to
    // close, and these three carry forward into the venue's payout
    // destination when they create one.
    //
    // Validated against PESONET_BANKS rather than accepting free text:
    // PayMongo matches this string character for character on upload, so a
    // typed bank name is a transfer row that gets rejected at the one
    // moment nobody is watching. Mirrors the same check BankDetailsForm
    // already applies to the settings-page version of these fields.
    //
    // STALENESS RISK, ACCEPTED KNOWINGLY: PESONET_BANKS is 124 strings
    // hand-copied from PayMongo's template, and its own comment says it
    // must be regenerated by hand when they publish a new one. Nothing
    // syncs it. The day PayMongo adds a bank, a legitimate applicant
    // banking there cannot submit — and because the field is a dropdown,
    // their bank simply will not be in the list, which reads as the
    // applicant's problem rather than ours. Free text would be worse (a
    // silent transfer rejection instead of a loud submit failure), so this
    // stays — but the message below says the list is ours and points at
    // support rather than implying the applicant typed something wrong.
    bankName: z
      .string()
      .trim()
      .min(1, "Choose your bank")
      // The `: boolean` return annotation is load-bearing, not decoration.
      // isPesonetBank is a type guard, and TypeScript 5.5+ also INFERS type
      // predicates through a wrapping arrow — either way .refine() would
      // narrow this field to the 124-member literal union, which
      // react-hook-form's Resolver then refuses to reconcile with a plain
      // string field. Annotating the return keeps it a plain boolean.
      .refine(
        (value): boolean => isPesonetBank(value),
        "Choose a bank from the list. If yours isn't there, contact support — our bank list may be out of date."
      ),
    bankAccountName: z.string().trim().min(2, "Enter the account holder's name").max(120),
    bankAccountNumber: z
      .string()
      .trim()
      .regex(/^[0-9]{6,20}$/, "Enter the account number — digits only, 6 to 20 of them."),
    // Same shape as signUpSchema's agreedToTerms — a plain boolean here,
    // checked with the rest of the object below so record_agreement-
    // shaped server-side logic never has to trust this value as proof of
    // anything by itself, only as what gated the submit button.
    agreedToOwnerAgreement: z.boolean(),
  })
  .refine((data) => data.agreedToOwnerAgreement === true, {
    message: "You must accept the Venue Owner Agreement to continue.",
    path: ["agreedToOwnerAgreement"],
  });
export type SubmitOwnerApplicationValues = z.infer<typeof submitOwnerApplicationSchema>;

/** Field groups per wizard step, for gating "Next" via react-hook-form's trigger(fields). */
export const OWNER_APPLICATION_STEP_FIELDS = [
  ["businessName", "businessPhone", "businessEmail"],
  ["venueName", "venueAddress", "venueCity", "venueDescription"],
  ["courtCount"],
  // Payout details gate this step rather than only the final submit, so an
  // applicant finds out here — not after filling in everything else.
  ["bankName", "bankAccountName", "bankAccountNumber"],
  [],
  [],
  [],
  ["hasLiabilityInsurance", "agreedToOwnerAgreement"],
] as const satisfies readonly (readonly (keyof SubmitOwnerApplicationValues)[])[];
